{
 "title": "Chia",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "plot_size",
    "label": "单个Plot大小（GB）",
    "query": "K32 : 101,K33 : 209,K34 : 430,K35 : 884"
   },
   { "name": "network_space_unit", "label": "全网算力单位", "query": "Pib : 1024, Eib : 1048576" }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "各Harvester Plot分布",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_plots", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "每日期望收益 (个)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "9216/max(network_space)/$network_space_unit/1024*$plot_size*sum(total_plots)"
    }
   ]
  },
  {
   "title": "挖到的XCH",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(xch_count)", "legendFormat": "挖到的XCH" }
   ]
  },
  {
   "title": "爆块预计时间",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "24/(9216/max(network_space)/$network_space_unit/1024*$plot_size*sum(total_plots))*2"
    }
   ]
  },
  {
   "title": "个人总算力（Tib）",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(total_plots) * $plot_size / 1024"
    }
   ]
  },
  {
   "title": "全网算力",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(network_space)" }
   ]
  },
  {
   "title": "Farm高度",
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(last_farm_height)" }
   ]
  },
  {
   "title": "各Harvester初筛通过率",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rate(eligible_plots[5m])*300)/(rate(number_of_challenges[5m])*300)*100",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "各Harvester验证挑战数量 （5分钟）",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 3, "x": 5, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(number_of_challenges[5m])*300",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "各Harvester爆块统计",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 3, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "proofs_found", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "概率统计 %",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(eligible_plots) / sum(number_of_challenges) * 100",
     "legendFormat": "初筛通过率"
    },
    {
     "expr": "sum(proofs_found) / sum(eligible_plots) * 100",
     "legendFormat": "初筛验证成功率"
    },
    {
     "expr": "sum(proofs_found) / sum(number_of_challenges) * 100",
     "legendFormat": "总爆块率"
    }
   ]
  },
  {
   "title": "挑战验证累计",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 3, "x": 19, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(number_of_challenges)", "legendFormat": "已查询挑战" },
    { "expr": "sum(eligible_plots)\n", "legendFormat": "通过初筛" },
    { "expr": "sum(proofs_found)", "legendFormat": "爆块" }
   ]
  },
  {
   "title": "查询挑战数量 (5分钟平均)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(number_of_challenges[5m])*300",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "挑战查询时间",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(check_duration_bucket[5m])) by (le))",
     "legendFormat": "平均查询时间"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(check_duration_bucket[5m])) by (le))",
     "legendFormat": "P95 查询时间"
    }
   ]
  }
 ]
}