{
 "title": "Chia Copy",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "plot_size",
    "label": "Tamaño de plot individual（GB）",
    "query": "K32 : 101,K33 : 209,K34 : 430,K35 : 884"
   },
   { "name": "network_space_unit", "label": "Unidad de tamaño de la red", "query": "Pib : 1024, Eib : 1048576" }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Plots en cada cosechador (harvester)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_plots", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "XCH diario estimado",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "9216/sum(network_space)/$network_space_unit/1024*$plot_size*sum(total_plots)"
    }
   ]
  },
  {
   "title": "XCH ganado",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "xch_count", "legendFormat": "挖到的XCH" }
   ]
  },
  {
   "title": "Tiempo estimado para ganar un bloque",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "24/(9216/sum(network_space)/$network_space_unit/1024*$plot_size*sum(total_plots))*2"
    }
   ]
  },
  {
   "title": "Tu espacio total（Tib）",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(total_plots) * $plot_size / 1024"
    }
   ]
  },
  {
   "title": "Espacio de la red",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "network_space" }
   ]
  },
  {
   "title": "Altura de la cosecha más reciente",
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "last_farm_height" }
   ]
  },
  {
   "title": "Filtros aprobados % en cada cosechador",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rate(eligible_plots[5m])*300)/(rate(number_of_challenges[5m])*300)*100",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Desafíos en cada cosechador (5min)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 3, "x": 5, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(number_of_challenges[5m])*300",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Ganancias en cada cosechador",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 3, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "proofs_found", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "Tasa de ganancias estáticas en porcentaje",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "por ciento" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(eligible_plots) / sum(number_of_challenges) * 100",
     "legendFormat": "Filtros aprobados"
    },
    {
     "expr": "sum(proofs_found) / sum(eligible_plots) * 100",
     "legendFormat": "Plots filtrados probados"
    },
    {
     "expr": "sum(proofs_found) / sum(number_of_challenges) * 100",
     "legendFormat": "Tasa experimental de ganancias"
    }
   ]
  },
  {
   "title": "Conteo de desafíos",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 3, "x": 19, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(number_of_challenges)", "legendFormat": "Desafíos totales" },
    { "expr": "sum(eligible_plots)\n", "legendFormat": "Filtros aprobados" },
    { "expr": "sum(proofs_found)", "legendFormat": "Ganado" }
   ]
  },
  {
   "title": "Desafíos promedio en cosechador (5min)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(number_of_challenges[5m])*300",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Latencia de desafíos",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(check_duration_bucket[5m])) by (le))",
     "legendFormat": "Average Check Duration"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(check_duration_bucket[5m])) by (le))",
     "legendFormat": "95th Percentile Check Duration"
    }
   ]
  }
 ]
}